# Form implementation generated from reading ui file 'invalpopup.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog1(object):
    def setupUi(self, Dialog1):
        Dialog1.setObjectName("Dialog1")
        Dialog1.resize(254, 192)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog1)
        self.buttonBox.setGeometry(QtCore.QRect(50, 160, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog1)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 213, 144))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.a1Label = QtWidgets.QLabel(parent=self.groupBox)
        self.a1Label.setObjectName("a1Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.a1Label)
        self.a1LineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.a1LineEdit.setObjectName("a1LineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.a1LineEdit)
        self.a2Label = QtWidgets.QLabel(parent=self.groupBox)
        self.a2Label.setObjectName("a2Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.a2Label)
        self.a2LineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.a2LineEdit.setObjectName("a2LineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.a2LineEdit)
        self.lambda1Label = QtWidgets.QLabel(parent=self.groupBox)
        self.lambda1Label.setObjectName("lambda1Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lambda1Label)
        self.lambda1LineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lambda1LineEdit.setObjectName("lambda1LineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lambda1LineEdit)
        self.lambda2Label = QtWidgets.QLabel(parent=self.groupBox)
        self.lambda2Label.setObjectName("lambda2Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lambda2Label)
        self.lambda2LineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lambda2LineEdit.setObjectName("lambda2LineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lambda2LineEdit)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog1)
        self.buttonBox.accepted.connect(Dialog1.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog1.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog1)

    def retranslateUi(self, Dialog1):
        _translate = QtCore.QCoreApplication.translate
        Dialog1.setWindowTitle(_translate("Dialog1", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog1", "Parameter Initial Value"))
        self.a1Label.setText(_translate("Dialog1", "A1"))
        self.a2Label.setText(_translate("Dialog1", "A2"))
        self.lambda1Label.setText(_translate("Dialog1", "Lambda 1"))
        self.lambda2Label.setText(_translate("Dialog1", "Lambda 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog1 = QtWidgets.QDialog()
    ui = Ui_Dialog1()
    ui.setupUi(Dialog1)
    Dialog1.show()
    sys.exit(app.exec())
